language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
before_script:
  - wget -O phpunit https://phar.phpunit.de/phpunit-5.phar
  - chmod +x phpunit
script:
  - ./phpunit test-phpunit.php
branches:
  except:
    - master